---
- name: Create facts directory
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory

- name: Write /etc/ansible/facts.d/foreman_installer.fact
  template:
    src: templates/foreman_installer.fact.rb.j2
    dest: /etc/ansible/facts.d/foreman_installer.fact
    mode: 0755
  notify:
    - reload ansible_local

- name: run notified handlers
  meta: flush_handlers
